import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast'
import ReduxProvider from "@/components/ReduxProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Netflix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>

          <Toaster position="top-center" reverseOrder={false} />

          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
